# Generated by Django 4.2.4 on 2023-08-31 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_comida_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria'),
        ),
    ]
